# analise de dados do Escola Inteligente 
- dados inep disponibilizado por api

A fonte de dados Ã© :http://educacao.dadosabertosbr.com/

In [5]:
#importando as bibliotecas 
import pandas as pd
import requests

#Url da api
url_api = 'http://educacao.dadosabertosbr.com/api/escolas/buscaavancada?situacaoFuncionamento=1&energiaInexistente=on&aguaInexistente=on&esgotoInexistente=on&cozinha=on'

#RequisitANDO api COM REQUESTS
resposta =requests.get(url_api)


#criando dataframe
df = pd.DataFrame(resposta.json()[1])
df.head()

,anoCenso,cod,nome,codCidade,cidade,estado,regiao,situacaoFuncionamento,dependenciaAdministrativa,idebAI,idebAF,enemMediaGeral,situacaoFuncionamentoTxt,dependenciaAdministrativaTxt
0,2013,41036026,BAIRRO DOS MENDES E R M EF,4104402,CANDIDO DE ABREU,PR,Sul,1,3,0.0,0.0,0.0,Em atividade,Municipal
1,2013,15008258,E M E F AGUA AZUL,1504802,MONTE ALEGRE,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal
2,2013,15534340,E M E F AGUA BOA,1505650,PLACAS,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal
3,2013,15525821,E M E F AMAZONIA,1505064,NOVO REPARTIMENTO,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal
4,2013,15022790,E M E F AMELIA HOLANDA,1500305,AFUA,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal

In [6]:
df.tail()

,anoCenso,cod,nome,codCidade,cidade,estado,regiao,situacaoFuncionamento,dependenciaAdministrativa,idebAI,idebAF,enemMediaGeral,situacaoFuncionamentoTxt,dependenciaAdministrativaTxt
95,2013,15103692,E M E F PRINCESA ISABEL,1506195,RUROPOLIS,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal
96,2013,15227499,E M E F PROF JONATHAS PONTES ATHIAS,1505106,OBIDOS,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal
97,2013,15556956,E M E F PROFESSORA ALDALETE FERREIRA,1500305,AFUA,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal
98,2013,15536521,E M E F RAIMUNDO DE SOUZA SANTOS,1504703,MOJU,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal
99,2013,15023664,E M E F RAIMUNDO NOGUEIRA,1500305,AFUA,PA,Norte,1,3,0.0,0.0,0.0,Em atividade,Municipal

In [7]:
df['estado'].value_counts()

PA    99
PR     1
Name: estado, dtype: int64

In [8]:
df['dependenciaAdministrativaTxt'].value_counts()

Municipal    100
Name: dependenciaAdministrativaTxt, dtype: int64